version: "2.2"

services:
  proxy:
    image: dobbs/proxy:latest
    init: true
    volumes:
      - proxy:/etc/proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDYPATH: /etc/proxy
    command:
      --conf
      /etc/proxy/Caddyfile
      --log
      stdout
      --agree
      --email
      ${LE_EMAIL}
  farm:
    image: dobbs/farm:latest
    init: true
    volumes:
      - dot-wiki:/home/app/.wiki
    environment:
      DOMAIN: wiki.dbbs.co
      COOKIE: secure
  images:
    image: dobbs/image-transporter
    init: true

volumes:
  dot-wiki:
    external:
      name: wiki.$DROPLET
  proxy:
    external:
      name: proxy.$DROPLET
