version: "2.2"

services:
  proxy:
    image: dobbs/proxy:0.10.12
    init: true
    volumes:
      - proxy:/etc/proxy
      - proxy.d:/etc/proxy.d
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDYPATH: /etc/proxy
      MAX_CERTS: 7
    command:
      /usr/bin/caddy
      --conf
      /etc/proxy/Caddyfile
      --log
      stdout
      --agree
      --email
      ${LE_EMAIL}
    restart: on-failure
  farm:
    image: dobbs/farm:0.14.0
    init: true
    volumes:
      - dot-wiki:/home/app/.wiki
    environment:
      DOMAIN: wiki.dbbs.co
      COOKIE: secure
    restart: on-failure
  images:
    image: dobbs/image-transporter
    init: true
    restart: on-failure
  apparatus:
    image: dobbs/apparatus
    init: true
    restart: on-failure
    volumes:
      - apparatus-saves:/src/saves

volumes:
  dot-wiki:
    external:
      name: wiki.$DROPLET
  proxy:
    external:
      name: proxy.$DROPLET
  proxy.d:
    external:
      name: proxy.d.$DROPLET
  apparatus-saves:
    external:
      name: apparatus-saves.$DROPLET
