version: "2.2"

services:
  proxy:
    image: dobbs/proxy:0.10.10
    init: true
    volumes:
      - proxy:/etc/proxy
      - proxy.d:/etc/proxy.d
      - proxy.certs:/etc/proxy.certs
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDYPATH: /etc/proxy.certs
      MAX_CERTS: 4
    command:
      --conf
      /etc/proxy/Caddyfile
      --log
      stdout
      --agree
      --email
      ${LE_EMAIL}
    restart: on-failure
  farm:
    image: dobbs/farm:0.12.2
    init: true
    volumes:
      - dot-wiki:/home/app/.wiki
    environment:
      DOMAIN: wiki.dbbs.co
      COOKIE: secure
    restart: on-failure
  images:
    image: dobbs/image-transporter
    init: true
    restart: on-failure

volumes:
  dot-wiki:
    external:
      name: wiki.$DROPLET
  proxy:
    external:
      name: proxy.$DROPLET
  proxy.d:
    external:
      name: proxy.d.$DROPLET
  proxy.certs:
    external:
      name: proxy.certs.$DROPLET
