version: "2.2"

services:
  caddy:
    image: caddy:2.7
    init: true
    volumes:
      - $PWD/Caddyfile2:/etc/caddy/Caddyfile
      - $PWD/caddy/data:/data
      - $PWD/caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
    environment:
      LE_EMAIL: $LE_EMAIL
      AUTH_DOMAIN: $AUTH_DOMAIN
      AUTH_NAME: $AUTH_NAME
      AUTH_PASS: $AUTH_PASS
    restart: on-failure
  farm:
    image: dobbs/farm:1.0.18
    init: true
    volumes:
      - dot-wiki:/home/node/.wiki
    restart: on-failure
  images:
    image: dobbs/image-transporter
    init: true
    restart: on-failure
  apparatus:
    image: dobbs/apparatus
    init: true
    restart: on-failure
    volumes:
      - apparatus-saves:/src/saves

volumes:
  dot-wiki:
    external:
      name: wiki.$DROPLET
  proxy:
    external:
      name: proxy.$DROPLET
  proxy.d:
    external:
      name: proxy.d.$DROPLET
  apparatus-saves:
    external:
      name: apparatus-saves.$DROPLET
